# -----------------------
# WOR-TEN (Mirakl Mirakl API)
# -----------------------
worten_api_base       = "https://marketplace.worten.pt/api/orders"
worten_shop_id        = "13810"
worten_api_key        = "0f6ce2d3-dcaf-4a9f-89b9-b6016fcedcbb"

# -----------------------
# LEROY MERLIN (ADEO MMP)
# -----------------------
# Base URL per le chiamate seller API
leroymerlin_api_base  = "https://adeo-marketplace.mirakl.net/api"
# Shop ID assegnato al tuo account
leroy_shop_id         = "8825"
# Utente e password (necessari solo se usi ancora Basic Auth)
leroy_username        = "domenicocuomo1977@gmail.com"
leroy_password        = "1z2x3c4v6B7*"
# API Key generata (Bearer token) per OR11 – List Orders
leroymerlin_api_key   = "e7b136dd-9908-4dd5-ae04-2867087d1f45"
