# -----------------------
# WOR-TEN (Mirakl API)
# -----------------------
worten_api_base = "https://marketplace.worten.pt/api/orders"
worten_shop_id = "13810"
worten_api_key = "0635f400-65e8-4c23-8335-03146399c3a0"

# -----------------------
# LEROY MERLIN (ADEO MMP)
# -----------------------
leroy_base_url = "https://adeo-marketplace.mirakl.net/api"
leroy_shop_id = "8825"
leroy_api_key = "e7b136dd-9908-4dd5-ae04-2867087d1f45"
