# -----------------------
# WOR-TEN (Mirakl Mirakl API)
# -----------------------
worten_api_base       = "https://marketplace.worten.pt/api/orders"
worten_shop_id        = "13810"
worten_api_key        = ""


